name: sergio_pizza
description: "Project sergio pizza"
publish_to: 'none' 


version: 0.1.0+1

environment:
  sdk: ^3.7.2





# изменить имя
# AndroidManifest.xml (located at android/app/src/main
# <application android:label="App Name" ...>
# info.plist (located at ios/Runner)
# <key>CFBundleDisplayName</key>
# <string>App Name</string>

#обязательно для удаления очищения данных
# <application android:allowBackup="false"
# android:fullBackupContent="false"
# в файле AndroidManifest.xml


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0 #https://pub.dev/packages/flutter_bloc
  bloc: ^9.0.0 #https://pub.dev/packages/bloc
  equatable: ^2.0.7 #https://pub.dev/packages/equatable
  page_transition: ^2.2.1 #https://pub.dev/packages/page_transition
  shared_preferences: ^2.5.3 #https://pub.dev/packages/shared_preferences
  flutter_launcher_icons: ^0.14.3 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^14.8.1 #https://pub.dev/packages/go_router
  get: ^4.7.2 #https://pub.dev/packages/get
  dio: ^5.8.0+1 #https://pub.dev/packages/dio
  gap: ^3.0.1 #https://pub.dev/packages/gap
  intl: ^0.20.2 #https://pub.dev/packages/intl
  flutter_easylogger: ^2.3.3 #https://pub.dev/packages/flutter_easylogger
  flutter_svg: ^2.0.17 #https://pub.dev/packages/flutter_svg
  package_info_plus: ^8.3.0 #https://pub.dev/packages/package_info_plus/install
  device_info_plus: ^11.3.3 #https://pub.dev/packages/device_info_plus
  geolocator: ^13.0.4 #https://pub.dev/packages/geolocator
  crypto: ^3.0.6 #https://pub.dev/packages/crypto
  pin_code_fields: ^8.0.1 #https://pub.dev/packages/pin_code_fields
  flutter_secure_storage: ^9.2.4 #https://pub.dev/packages/flutter_secure_storage
  geocoding: ^3.0.0 #https://pub.dev/packages/geocoding
  # flutter_carousel_widget: ^3.1.0 #https://pub.dev/packages/flutter_carousel_widget
  cached_network_svg_image: ^1.2.0 #https://pub.dev/packages/cached_network_svg_image
  share_plus: ^10.1.4 #https://pub.dev/packages/share_plus
  # swipeable_page_route: ^0.4.7 #https://pub.dev/packages/swipeable_page_route
  flutter_cupertino_datetime_picker: ^3.0.0 #https://pub.dev/packages/flutter_cupertino_datetime_picker
  # url_launcher: ^6.3.1 #https://pub.dev/packages/url_launcher
  # flutter_cached_image: 
  #   git:
  #     url: https://github.com/Nykolayr/flutter_cached_image.git
  #     ref: f515daf6f20ccfcc7c284deef2dae0f2f6b64afe
  # table_calendar: ^3.2.0 #https://pub.dev/packages/table_calendar
  # webview_flutter: ^4.10.0 #https://pub.dev/packages/webview_flutter
  # webview_flutter_wkwebview: ^3.18.5 #https://pub.dev/packages/webview_flutter_wkwebview
  # google_fonts: ^6.2.1 #https://pub.dev/packages/google_fonts
    

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true  
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo.png
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/logo.png" 


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ProximaNova
      fonts:
        # Black
        - asset: assets/fonts/ProximaNova-Black.ttf
          weight: 900
        - asset: assets/fonts/ProximaNova-BlackIt.ttf
          weight: 900
          style: italic
          
        # Bold
        - asset: assets/fonts/ProximaNova-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProximaNova-BoldIt.ttf
          weight: 700
          style: italic
          
        # Extrabold
        - asset: assets/fonts/ProximaNova-Extrabld.ttf
          weight: 800
        - asset: assets/fonts/ProximaNova-ExtrabldIt.ttf
          weight: 800
          style: italic
          
        # Light
        - asset: assets/fonts/ProximaNova-Light.ttf
          weight: 300
        - asset: assets/fonts/ProximaNova-LightIt.ttf
          weight: 300
          style: italic
          
        # Regular
        - asset: assets/fonts/ProximaNova-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProximaNova-RegularIt.ttf
          weight: 400
          style: italic
          
        # Semibold
        - asset: assets/fonts/ProximaNova-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ProximaNova-SemiboldIt.ttf
          weight: 600
          style: italic
          
        # Thin
        - asset: assets/fonts/ProximaNova-ThinIt.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/ProximaNovaT-Thin.ttf
          weight: 100

